name: Export Google Sheet to public data

on:
  workflow_dispatch:
  schedule:
    # (horaires inchangés ici pour la lisibilité)

permissions:
  contents: write

concurrency:
  group: export-sheets
  cancel-in-progress: false

jobs:
  export:
    # ne lance le workflow qu’après la réussite d’un workflow_run
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export sheet to CSV/JSON
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # Liste des onglets existants ; chaque plage commence en A1 et s’étend jusqu’à Z (colonnes 1 à 26)
          SHEET_RANGE: "'0-5min'!A1:Z,'5-10min'!A1:Z,'10-20min'!A1:Z,'20-30min'!A1:Z,'30-40min'!A1:Z,'40-50min'!A1:Z,'50-60min'!A1:Z,'60Plusmin'!A1:Z"
        run: python scripts/export_sheet.py

      - name: Commit & push CSV and JSON update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add bolt-app/public/data/videos.csv bolt-app/public/data/videos.json
          if git diff --cached --quiet; then
            echo "Data files have not changed. Nothing to commit."
            exit 0
          fi
          git commit -m "chore: update exported data"
          git push origin HEAD:main
