name: YouTube to Sheets Sync

on:
  workflow_dispatch: # Seul le déclenchement manuel est activé

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Mise à jour de l'action checkout à la version 3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        # Mise à jour de l'action setup-python à la version 4

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json
          python main.py
