name: YouTube to Sheets Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"   # Tous les jours à 07:00 UTC. 08:00 en hiver à Paris, 09:00 en été.

permissions:
  contents: read

concurrency:
  group: youtube-to-sheets-sync
  cancel-in-progress: false

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run tests
        run: pytest -q

  sync:
    name: Sync playlist to Google Sheets
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google service account key
        run: |
          printf '%s' "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run sync
        run: python main.py
