name: YouTube to Sheets Sync

on:
  workflow_dispatch:  # Pour lancer manuellement depuis l'interface GitHub
  push:
    branches: [ main ]

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter le script de synchronisation
        run: python main.py

      - name: Upload artifact (log)
        uses: actions/upload-artifact@v3
        with:
          name: sync-log
          path: log.txt  # Vérifie que ce fichier existe ou ajuste le chemin
