name: YouTube to Sheets Sync

on:
  # La synchronisation automatique est désactivée
  # schedule:
  #   - cron: '0 6 * * *' # Exécute le workflow tous les jours à 6h du matin UTC
  workflow_dispatch: # Permet de lancer manuellement le workflow depuis l'onglet Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # Cette étape clone le code du dépôt dans l'environnement du workflow

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        # Installe Python 3.9 pour exécuter le script

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests
        # Installe les dépendances Python nécessaires

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          # On recrée le fichier service_account.json à partir du secret
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json

          # Lancement du script Python principal
          python main.py
        # Cette étape :
        # 1. Récupère les secrets et les met dans les variables d'environnement.
        # 2. Crée le fichier service_account.json à partir du secret.
        # 3. Lance le script main.py qui va :
        #    - Appeler l'API YouTube Data avec YOUTUBE_API_KEY
        #    - Mettre à jour le Google Sheet via le compte de service
